# Generated by Django 3.2.6 on 2021-08-25 13:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Shreekrupa Agarbatti', max_length=255, unique=True)),
                ('subtitle', models.CharField(default='Best Place for Fragrance Agarbatti!', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='Home/')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('tag', models.CharField(choices=[('Featured', 'Featured'), ('Recent', 'Recent')], max_length=50)),
                ('category', models.CharField(choices=[('Agarbatti', 'Agarbatti'), ('Dhoopbatti', 'Dhoopbatti'), ('Perfume', 'Perfume')], max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('related_home', models.ForeignKey(default='shreekrupa-agarbatti', on_delete=django.db.models.deletion.CASCADE, to='ProjectDesign.home')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ProductImage/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectDesign.product')),
            ],
        ),
    ]
